//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webshop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Raktar> Raktar { get; set; }
        public virtual DbSet<Rendeles> Rendeles { get; set; }
        public virtual DbSet<Rendeles_tetel> Rendeles_tetel { get; set; }
        public virtual DbSet<Termek> Termek { get; set; }
        public virtual DbSet<Termekkategoria> Termekkategoria { get; set; }
        public virtual DbSet<Ugyfel> Ugyfel { get; set; }
    }
}
