//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendeles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rendeles()
        {
            this.Rendeles_tetel = new HashSet<Rendeles_tetel>();
        }
    
        public int SORSZAM { get; set; }
        public string LOGIN { get; set; }
        public Nullable<System.DateTime> REND_DATUM { get; set; }
        public Nullable<System.DateTime> SZALL_DATUM { get; set; }
        public string SZALL_CIM { get; set; }
        public string SZALL_MOD { get; set; }
        public string FIZ_MOD { get; set; }
        public string SZAMLA_CIM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendeles_tetel> Rendeles_tetel { get; set; }
        public virtual Ugyfel Ugyfel { get; set; }
    }
}
