//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendeles_tetel
    {
        public int SORSZAM { get; set; }
        public string TERMEKKOD { get; set; }
        public Nullable<double> EGYSEGAR { get; set; }
        public double MENNYISEG { get; set; }
    
        public virtual Rendeles Rendeles { get; set; }
        public virtual Termek Termek { get; set; }
    }
}
