//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termek()
        {
            this.Rendeles_tetel = new HashSet<Rendeles_tetel>();
        }
    
        public string TERMEKKOD { get; set; }
        public string MEGNEVEZES { get; set; }
        public Nullable<int> KAT_ID { get; set; }
        public Nullable<double> LISTAAR { get; set; }
        public string LEIRAS { get; set; }
        public Nullable<int> RAKTAR_KOD { get; set; }
        public Nullable<double> KESZLET { get; set; }
        public string MEGYS { get; set; }
        public string FELVITTE { get; set; }
        public Nullable<System.DateTime> FELVITEL { get; set; }
    
        public virtual Raktar Raktar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendeles_tetel> Rendeles_tetel { get; set; }
        public virtual Termekkategoria Termekkategoria { get; set; }
    }
}
