//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termekkategoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termekkategoria()
        {
            this.Termek = new HashSet<Termek>();
            this.Termekkategoria1 = new HashSet<Termekkategoria>();
        }
    
        public int KAT_ID { get; set; }
        public string KAT_NEV { get; set; }
        public Nullable<int> SZULO_KAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Termek> Termek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Termekkategoria> Termekkategoria1 { get; set; }
        public virtual Termekkategoria Termekkategoria2 { get; set; }
    }
}
